name: flutter_vitual_keyboard
description: A flutter virtual keyboard plugin
version: 0.0.1-dev
publish_to: none
homepage: https://github.com/itschillipill/flutter-virtual-keyboard
repository: https://github.com/itschillipill/flutter-virtual-keyboard
issue_tracker: https://github.com/itschillipill/flutter-virtual-keyboard/issues
license: MIT

topics: 
  - keyboard
  - vitual keyboard
  - cross-platform
  - flutter

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment: 
  sdk: ">=3.0.0 <4.0.0"

dependencies: 
  flutter:
    sdk: flutter
  provider: ^6.1.5+1

flutter:
  uses-material-design: true